# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julien/Desktop/projet-logiciel-kine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julien/Desktop/projet-logiciel-kine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julien/Desktop/projet-logiciel-kine/CMakeFiles /home/julien/Desktop/projet-logiciel-kine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julien/Desktop/projet-logiciel-kine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Kinesia

# Build rule for target.
Kinesia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Kinesia
.PHONY : Kinesia

# fast build rule for target.
Kinesia/fast:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/build
.PHONY : Kinesia/fast

src/controller/BDD_to_struct_folder.o: src/controller/BDD_to_struct_folder.c.o

.PHONY : src/controller/BDD_to_struct_folder.o

# target to build an object file
src/controller/BDD_to_struct_folder.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_folder.c.o
.PHONY : src/controller/BDD_to_struct_folder.c.o

src/controller/BDD_to_struct_folder.i: src/controller/BDD_to_struct_folder.c.i

.PHONY : src/controller/BDD_to_struct_folder.i

# target to preprocess a source file
src/controller/BDD_to_struct_folder.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_folder.c.i
.PHONY : src/controller/BDD_to_struct_folder.c.i

src/controller/BDD_to_struct_folder.s: src/controller/BDD_to_struct_folder.c.s

.PHONY : src/controller/BDD_to_struct_folder.s

# target to generate assembly for a file
src/controller/BDD_to_struct_folder.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_folder.c.s
.PHONY : src/controller/BDD_to_struct_folder.c.s

src/controller/BDD_to_struct_patient.o: src/controller/BDD_to_struct_patient.c.o

.PHONY : src/controller/BDD_to_struct_patient.o

# target to build an object file
src/controller/BDD_to_struct_patient.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_patient.c.o
.PHONY : src/controller/BDD_to_struct_patient.c.o

src/controller/BDD_to_struct_patient.i: src/controller/BDD_to_struct_patient.c.i

.PHONY : src/controller/BDD_to_struct_patient.i

# target to preprocess a source file
src/controller/BDD_to_struct_patient.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_patient.c.i
.PHONY : src/controller/BDD_to_struct_patient.c.i

src/controller/BDD_to_struct_patient.s: src/controller/BDD_to_struct_patient.c.s

.PHONY : src/controller/BDD_to_struct_patient.s

# target to generate assembly for a file
src/controller/BDD_to_struct_patient.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_patient.c.s
.PHONY : src/controller/BDD_to_struct_patient.c.s

src/controller/BDD_to_struct_session.o: src/controller/BDD_to_struct_session.c.o

.PHONY : src/controller/BDD_to_struct_session.o

# target to build an object file
src/controller/BDD_to_struct_session.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_session.c.o
.PHONY : src/controller/BDD_to_struct_session.c.o

src/controller/BDD_to_struct_session.i: src/controller/BDD_to_struct_session.c.i

.PHONY : src/controller/BDD_to_struct_session.i

# target to preprocess a source file
src/controller/BDD_to_struct_session.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_session.c.i
.PHONY : src/controller/BDD_to_struct_session.c.i

src/controller/BDD_to_struct_session.s: src/controller/BDD_to_struct_session.c.s

.PHONY : src/controller/BDD_to_struct_session.s

# target to generate assembly for a file
src/controller/BDD_to_struct_session.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/BDD_to_struct_session.c.s
.PHONY : src/controller/BDD_to_struct_session.c.s

src/controller/UI_to_struct.o: src/controller/UI_to_struct.c.o

.PHONY : src/controller/UI_to_struct.o

# target to build an object file
src/controller/UI_to_struct.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/UI_to_struct.c.o
.PHONY : src/controller/UI_to_struct.c.o

src/controller/UI_to_struct.i: src/controller/UI_to_struct.c.i

.PHONY : src/controller/UI_to_struct.i

# target to preprocess a source file
src/controller/UI_to_struct.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/UI_to_struct.c.i
.PHONY : src/controller/UI_to_struct.c.i

src/controller/UI_to_struct.s: src/controller/UI_to_struct.c.s

.PHONY : src/controller/UI_to_struct.s

# target to generate assembly for a file
src/controller/UI_to_struct.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/UI_to_struct.c.s
.PHONY : src/controller/UI_to_struct.c.s

src/controller/display_helpers.o: src/controller/display_helpers.c.o

.PHONY : src/controller/display_helpers.o

# target to build an object file
src/controller/display_helpers.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/display_helpers.c.o
.PHONY : src/controller/display_helpers.c.o

src/controller/display_helpers.i: src/controller/display_helpers.c.i

.PHONY : src/controller/display_helpers.i

# target to preprocess a source file
src/controller/display_helpers.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/display_helpers.c.i
.PHONY : src/controller/display_helpers.c.i

src/controller/display_helpers.s: src/controller/display_helpers.c.s

.PHONY : src/controller/display_helpers.s

# target to generate assembly for a file
src/controller/display_helpers.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/display_helpers.c.s
.PHONY : src/controller/display_helpers.c.s

src/controller/extern_files_manager.o: src/controller/extern_files_manager.c.o

.PHONY : src/controller/extern_files_manager.o

# target to build an object file
src/controller/extern_files_manager.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/extern_files_manager.c.o
.PHONY : src/controller/extern_files_manager.c.o

src/controller/extern_files_manager.i: src/controller/extern_files_manager.c.i

.PHONY : src/controller/extern_files_manager.i

# target to preprocess a source file
src/controller/extern_files_manager.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/extern_files_manager.c.i
.PHONY : src/controller/extern_files_manager.c.i

src/controller/extern_files_manager.s: src/controller/extern_files_manager.c.s

.PHONY : src/controller/extern_files_manager.s

# target to generate assembly for a file
src/controller/extern_files_manager.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/extern_files_manager.c.s
.PHONY : src/controller/extern_files_manager.c.s

src/controller/struct_to_BDD_folder.o: src/controller/struct_to_BDD_folder.c.o

.PHONY : src/controller/struct_to_BDD_folder.o

# target to build an object file
src/controller/struct_to_BDD_folder.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_folder.c.o
.PHONY : src/controller/struct_to_BDD_folder.c.o

src/controller/struct_to_BDD_folder.i: src/controller/struct_to_BDD_folder.c.i

.PHONY : src/controller/struct_to_BDD_folder.i

# target to preprocess a source file
src/controller/struct_to_BDD_folder.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_folder.c.i
.PHONY : src/controller/struct_to_BDD_folder.c.i

src/controller/struct_to_BDD_folder.s: src/controller/struct_to_BDD_folder.c.s

.PHONY : src/controller/struct_to_BDD_folder.s

# target to generate assembly for a file
src/controller/struct_to_BDD_folder.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_folder.c.s
.PHONY : src/controller/struct_to_BDD_folder.c.s

src/controller/struct_to_BDD_patient.o: src/controller/struct_to_BDD_patient.c.o

.PHONY : src/controller/struct_to_BDD_patient.o

# target to build an object file
src/controller/struct_to_BDD_patient.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_patient.c.o
.PHONY : src/controller/struct_to_BDD_patient.c.o

src/controller/struct_to_BDD_patient.i: src/controller/struct_to_BDD_patient.c.i

.PHONY : src/controller/struct_to_BDD_patient.i

# target to preprocess a source file
src/controller/struct_to_BDD_patient.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_patient.c.i
.PHONY : src/controller/struct_to_BDD_patient.c.i

src/controller/struct_to_BDD_patient.s: src/controller/struct_to_BDD_patient.c.s

.PHONY : src/controller/struct_to_BDD_patient.s

# target to generate assembly for a file
src/controller/struct_to_BDD_patient.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_patient.c.s
.PHONY : src/controller/struct_to_BDD_patient.c.s

src/controller/struct_to_BDD_session.o: src/controller/struct_to_BDD_session.c.o

.PHONY : src/controller/struct_to_BDD_session.o

# target to build an object file
src/controller/struct_to_BDD_session.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_session.c.o
.PHONY : src/controller/struct_to_BDD_session.c.o

src/controller/struct_to_BDD_session.i: src/controller/struct_to_BDD_session.c.i

.PHONY : src/controller/struct_to_BDD_session.i

# target to preprocess a source file
src/controller/struct_to_BDD_session.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_session.c.i
.PHONY : src/controller/struct_to_BDD_session.c.i

src/controller/struct_to_BDD_session.s: src/controller/struct_to_BDD_session.c.s

.PHONY : src/controller/struct_to_BDD_session.s

# target to generate assembly for a file
src/controller/struct_to_BDD_session.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/controller/struct_to_BDD_session.c.s
.PHONY : src/controller/struct_to_BDD_session.c.s

src/model/folder_manager.o: src/model/folder_manager.c.o

.PHONY : src/model/folder_manager.o

# target to build an object file
src/model/folder_manager.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/folder_manager.c.o
.PHONY : src/model/folder_manager.c.o

src/model/folder_manager.i: src/model/folder_manager.c.i

.PHONY : src/model/folder_manager.i

# target to preprocess a source file
src/model/folder_manager.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/folder_manager.c.i
.PHONY : src/model/folder_manager.c.i

src/model/folder_manager.s: src/model/folder_manager.c.s

.PHONY : src/model/folder_manager.s

# target to generate assembly for a file
src/model/folder_manager.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/folder_manager.c.s
.PHONY : src/model/folder_manager.c.s

src/model/patient_manager.o: src/model/patient_manager.c.o

.PHONY : src/model/patient_manager.o

# target to build an object file
src/model/patient_manager.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/patient_manager.c.o
.PHONY : src/model/patient_manager.c.o

src/model/patient_manager.i: src/model/patient_manager.c.i

.PHONY : src/model/patient_manager.i

# target to preprocess a source file
src/model/patient_manager.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/patient_manager.c.i
.PHONY : src/model/patient_manager.c.i

src/model/patient_manager.s: src/model/patient_manager.c.s

.PHONY : src/model/patient_manager.s

# target to generate assembly for a file
src/model/patient_manager.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/patient_manager.c.s
.PHONY : src/model/patient_manager.c.s

src/model/session_manager.o: src/model/session_manager.c.o

.PHONY : src/model/session_manager.o

# target to build an object file
src/model/session_manager.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/session_manager.c.o
.PHONY : src/model/session_manager.c.o

src/model/session_manager.i: src/model/session_manager.c.i

.PHONY : src/model/session_manager.i

# target to preprocess a source file
src/model/session_manager.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/session_manager.c.i
.PHONY : src/model/session_manager.c.i

src/model/session_manager.s: src/model/session_manager.c.s

.PHONY : src/model/session_manager.s

# target to generate assembly for a file
src/model/session_manager.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/model/session_manager.c.s
.PHONY : src/model/session_manager.c.s

src/view/editor_views.o: src/view/editor_views.c.o

.PHONY : src/view/editor_views.o

# target to build an object file
src/view/editor_views.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/editor_views.c.o
.PHONY : src/view/editor_views.c.o

src/view/editor_views.i: src/view/editor_views.c.i

.PHONY : src/view/editor_views.i

# target to preprocess a source file
src/view/editor_views.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/editor_views.c.i
.PHONY : src/view/editor_views.c.i

src/view/editor_views.s: src/view/editor_views.c.s

.PHONY : src/view/editor_views.s

# target to generate assembly for a file
src/view/editor_views.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/editor_views.c.s
.PHONY : src/view/editor_views.c.s

src/view/home_view.o: src/view/home_view.c.o

.PHONY : src/view/home_view.o

# target to build an object file
src/view/home_view.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/home_view.c.o
.PHONY : src/view/home_view.c.o

src/view/home_view.i: src/view/home_view.c.i

.PHONY : src/view/home_view.i

# target to preprocess a source file
src/view/home_view.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/home_view.c.i
.PHONY : src/view/home_view.c.i

src/view/home_view.s: src/view/home_view.c.s

.PHONY : src/view/home_view.s

# target to generate assembly for a file
src/view/home_view.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/home_view.c.s
.PHONY : src/view/home_view.c.s

src/view/main_UI.o: src/view/main_UI.c.o

.PHONY : src/view/main_UI.o

# target to build an object file
src/view/main_UI.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/main_UI.c.o
.PHONY : src/view/main_UI.c.o

src/view/main_UI.i: src/view/main_UI.c.i

.PHONY : src/view/main_UI.i

# target to preprocess a source file
src/view/main_UI.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/main_UI.c.i
.PHONY : src/view/main_UI.c.i

src/view/main_UI.s: src/view/main_UI.c.s

.PHONY : src/view/main_UI.s

# target to generate assembly for a file
src/view/main_UI.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/main_UI.c.s
.PHONY : src/view/main_UI.c.s

src/view/work_view.o: src/view/work_view.c.o

.PHONY : src/view/work_view.o

# target to build an object file
src/view/work_view.c.o:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/work_view.c.o
.PHONY : src/view/work_view.c.o

src/view/work_view.i: src/view/work_view.c.i

.PHONY : src/view/work_view.i

# target to preprocess a source file
src/view/work_view.c.i:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/work_view.c.i
.PHONY : src/view/work_view.c.i

src/view/work_view.s: src/view/work_view.c.s

.PHONY : src/view/work_view.s

# target to generate assembly for a file
src/view/work_view.c.s:
	$(MAKE) -f CMakeFiles/Kinesia.dir/build.make CMakeFiles/Kinesia.dir/src/view/work_view.c.s
.PHONY : src/view/work_view.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Kinesia"
	@echo "... src/controller/BDD_to_struct_folder.o"
	@echo "... src/controller/BDD_to_struct_folder.i"
	@echo "... src/controller/BDD_to_struct_folder.s"
	@echo "... src/controller/BDD_to_struct_patient.o"
	@echo "... src/controller/BDD_to_struct_patient.i"
	@echo "... src/controller/BDD_to_struct_patient.s"
	@echo "... src/controller/BDD_to_struct_session.o"
	@echo "... src/controller/BDD_to_struct_session.i"
	@echo "... src/controller/BDD_to_struct_session.s"
	@echo "... src/controller/UI_to_struct.o"
	@echo "... src/controller/UI_to_struct.i"
	@echo "... src/controller/UI_to_struct.s"
	@echo "... src/controller/display_helpers.o"
	@echo "... src/controller/display_helpers.i"
	@echo "... src/controller/display_helpers.s"
	@echo "... src/controller/extern_files_manager.o"
	@echo "... src/controller/extern_files_manager.i"
	@echo "... src/controller/extern_files_manager.s"
	@echo "... src/controller/struct_to_BDD_folder.o"
	@echo "... src/controller/struct_to_BDD_folder.i"
	@echo "... src/controller/struct_to_BDD_folder.s"
	@echo "... src/controller/struct_to_BDD_patient.o"
	@echo "... src/controller/struct_to_BDD_patient.i"
	@echo "... src/controller/struct_to_BDD_patient.s"
	@echo "... src/controller/struct_to_BDD_session.o"
	@echo "... src/controller/struct_to_BDD_session.i"
	@echo "... src/controller/struct_to_BDD_session.s"
	@echo "... src/model/folder_manager.o"
	@echo "... src/model/folder_manager.i"
	@echo "... src/model/folder_manager.s"
	@echo "... src/model/patient_manager.o"
	@echo "... src/model/patient_manager.i"
	@echo "... src/model/patient_manager.s"
	@echo "... src/model/session_manager.o"
	@echo "... src/model/session_manager.i"
	@echo "... src/model/session_manager.s"
	@echo "... src/view/editor_views.o"
	@echo "... src/view/editor_views.i"
	@echo "... src/view/editor_views.s"
	@echo "... src/view/home_view.o"
	@echo "... src/view/home_view.i"
	@echo "... src/view/home_view.s"
	@echo "... src/view/main_UI.o"
	@echo "... src/view/main_UI.i"
	@echo "... src/view/main_UI.s"
	@echo "... src/view/work_view.o"
	@echo "... src/view/work_view.i"
	@echo "... src/view/work_view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

