CREATE TABLE patient ( id INTEGER PRIMARY KEY AUTOINCREMENT, 
name VARCHAR(100) NOT NULL, 
firstname VARCHAR(100) NOT NULL, 
birthdate_year INTEGER, 
birthdate_month INTEGER, 
birthdate_day INTEGER, 
place_birth VARCHAR(100),
gender INTEGER,
phone_number VARCHAR(20),
mail_adress VARCHAR(100),
ssn VARCHAR(100),
weight INTEGER,
height INTEGER,
first_consultation_year INTEGER, 
first_consultation_month INTEGER, 
first_consultation_day INTEGER,
global_pathologies VARCHAR(300),
number VARCHAR(20),
street VARCHAR(100), 
postCode VARCHAR(50),
city VARCHAR(100),
other_info VARCHAR(100),
job VARCHAR(100));

CREATE TABLE seance ( idSeance INTEGER PRIMARY KEY AUTOINCREMENT, 
idDossier INTEGER, 
dateSeance_year INTEGER,
dateSeance_month INTEGER,
dateSeance_day INTEGER, 
DateSeanceSuiv_year INTEGER,
DateSeanceSuiv_month INTEGER,
DateSeanceSuiv_day INTEGER, 
observations VARCHAR(500));
