#!/bin/bash
today=$(date +"%Y-%m-%d-%H-%M-%S")
wd=$(pwd)

# request user authorization
while true; do
    read -p "Do you want to run test in ${wd}? (y/n) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

# ask for kind of test
while true; do
    read -p "What test do you want to process? (unit_test u / coverage c /memory m) " ucm
    case $ucm in
        [Uu]* )
          echo "*** Unit tests selected ***"
          mkdir cmocka && cd cmocka
          cmake ..
          cmake --build . --config
          ctest -C "Release"
          cd ../
          mv cmocka/Testing/Temporary/LastTest.log unitreport-${today}.log
          rm -rf cmocka
          echo "*** Unit tests done ***"
          break;;
        [Cc]* )
          echo "*** Coverage tests selected ***"
          rm -rf coverage
          make
          make cov_test
          mv covreport covreport-${today}
          make clean
          echo "*** Coverage tests done ***"
          exit;;
        [Mm]* )
          echo "*** Memory tests selected ***"
          make
          make mem_test
          mv memreport memreport-${today}.log
          make clean
          echo "*** Memory tests done ***"
          exit;;
        * ) echo "Please answer u, c or m.";;
    esac
done


